language: node_js

node_js:
  - 0.10.33

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - node tests/support/server/index.js &
  - sleep 5
script: npm test

notifications:
  slack: reallyio:1Aieu5uNy7ucflfQnjGJbFPY
